class POSErrorCode:
    # Generic
    INVALID_REQUEST = "INVALID_REQUEST"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"    
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_JSON = "INVALID_JSON"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

    # Purchase Order
    INVALID_COMPANY = "INVALID_COMPANY"
    INVALID_SUPPLIER = "INVALID_SUPPLIER"
    INVALID_ITEMS = "INVALID_ITEMS"
    INVALID_ITEM = "INVALID_ITEM"
    INVALID_QTY = "INVALID_QTY"
    INVALID_MATERIAL_REQUEST = "INVALID_MATERIAL_REQUEST"
    INVALID_WAREHOUSE = "INVALID_WAREHOUSE"
    PO_CREATED = "PO_CREATED"
    PO_CREATE_FAILED = "PO_CREATE_FAILED"
    
    LPO_NOT_FOUND = "PO_NOT_FOUND"
    PO_ALREADY_SUBMITTED = "ALREADY_SUBMITTED"
    LPO_CANCELLED = "LPO_CANCELLED"

    # GRN / Purchase Receipt
    QTY_EXCEEDS_ORDERED = "QTY_EXCEEDS_ORDERED"
    PO_NOT_SUBMITTED = "PO_NOT_SUBMITTED"
    GRN_NOT_RECEIVED = "GRN_NOT_RECEIVED"  
    GRN_ALREADY_APPLIED = "GRN_ALREADY_APPLIED"

    # Stock
    STOCK_ERROR = "STOCK_ERROR"
    
    SUCCESS = "POS_0000"

    INVALID_JSON = "POS_1001"
    INVALID_REQUEST = "POS_1002"
    PERMISSION_DENIED = "POS_1003"

    INVALID_WAREHOUSE = "POS_2001"
    QTY_EXCEEDS_ORDERED = "POS_2002"

    NOT_FOUND = "POS_3001"

    UNKNOWN_ERROR = "POS_9000"
    
    LPO_NOT_FOUND = "LPO_NOT_FOUND"
    GRN_NOT_FOUND = "GRN_NOT_FOUND"
    PI_CREATION_FAILED = "PI_CREATION_FAILED"
    INVALID_JSON = "INVALID_JSON"
    CREATION_FAILED = "POS_9001" 
    CURRENCY_MISMATCH = "POS_1003"